name: Update and deploy

on:
    # workflow_dispatch:
    schedule:
        - cron: '10/10 * * * *'  # Executar a cada 10 minutos
# on:
#     push:
#         branches:
#         - main

jobs:
  update_and_deploy:
    permissions:
        contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run script to fetch and process data
        run: node app.js

      - name: Move graph to output directory
        run: mv grafico.png docs/ || true  # Adicionado '|| true' para ignorar erro se o arquivo não existir
      - name: Move index.html to docs directory
        run: mv index.html docs/ || true  # Adicionado '|| true' para ignorar erro se o arquivo não existir


      - name: Commit and push changes
        run: |
          git config --global user.email "luizdavilaf@gmail.com"
          git config --global user.name "Luiz DAvila"
          git add -A  # Adicionado para adicionar todos os arquivos modificados, incluindo os da pasta 'docs'
          git diff-index --quiet HEAD || git commit -m "Update graph"  # Verifica se há alterações antes de commitar
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
